=== holistic-web/portfolio-fabricator/portfolio-management/portfolio.schema.json
{
	"$schema": "http://json-schema.org/schema#",
	"title": "Portfolio",
	"type": "object",
	"required": ["name", "profession", "aboutMe"],
	"properties": {
		"name": {
			"type": "object",
			"required": ["first", "last"],
			"properties": {
				"first": {
					"type": "string",
					"description": "First name of the portfolio creator"
				},
				"last": {
					"type": "string",
					"description": "Last name of the portfolio creator"
				}
			}
		},
		"profession": {
			"type": "string",
			"description": "Proffession to display on the portfolio"
		},
		"aboutMe": {
			"type": "string",
			"description": "A brief description of the porfolio creator"
		},
		"profileImageUrl": {
			"type": "string",
			"description": "Web url to access the provided profile image"
		},
		"contact": {
			"type": "object",
			"properties": {
				"email": {
					"type": "string",
					"description": "Public email address"
				},
				"telephone": {
					"type": "string",
					"description": "Public telephone number"
				}
			}
		},
		"externalProfiles": {
			"type": "object",
			"properties": {
				"github": {
					"type": "string",
					"description": "github profile name"
				},
				"linkenIn": {
					"type": "string",
					"description": "linkenIn profile name"
				},
				"stackOverflow": {
					"type": "string",
					"description": "Stack Overflow profile name"
				}
			}
		},
		"education": {
			"type": "array",
			"items": {
				"type": "object",
				"required": ["institution", "date"],
				"properties": {
					"institution": {
						"type": "string",
						"description": "Name of the education establishment"
					},
					"date": {
						"type": "string",
						"description": "When the institution was attended"
					},
					"qualifications": {
						"type": "array",
						"items": {
							"type": "string",
							"description": "Qualification achieved at the instution"
						}
					}
				}
			}
		},
		"experience": {
			"type": "array",
			"items": {
				"type": "object",
				"required": ["organization", "date", "description"],
				"properties": {
					"organization": {
						"type": "string",
						"description": "Name of the organizaton"
					},
					"date": {
						"type": "string",
						"description": "When work was done with the organization"
					},
					"description": {
						"type": "string",
						"description": "Brief description of the role"
					},
					"projects": {
						"type": "array",
						"items": {
							"type": "string",
							"description": "Projects worked on at the organization"
						}
					}
				}
			}
		}
	}
}

=== holistic-web/portfolio-fabricator/fabricated-website/src/lib/portfolioFallback.json
{
	"aboutMe":"King in the North and a bastard of Lord Eddard Stark. I ride dragons and kill white walkers and stuff. Don't @ me.",
	"contact":{
		"email":"kinginthenorth2019@gmail.com"
	},
	"education":[
		{
			"date":"Seasons 1 - 3 (ish)",
			"institution":"Winterfell",
			"qualifications":[
				"A+ in being a bastard",
				"B in husky training",
				"F in being with Ros"
			]
		}
	],
	"experience":[
		{
			"date":"Seasons 3 - 5 (ish)",
			"description":"I held the wall guarding the realms of men.",
			"organization":"Night's Watch",
			"projects":[
				"I went over the wall and killed some undead peeps, I did this using valerian steel.",
				"I hooked up with a wildling one time. That was jokes.",
				"I was killed and came back to life showing my persistence and determination."
			],
			"role":"Bossman"
		},
		{
			"date":"Seasons 7 - 8",
			"description":"So it turns out I'm actually son of Rhaegar Targaryen and Leanna Stark and rightful King.",
			"organization":"Targaryen Conquest",
			"projects":[
				"Defeated the army of the undead at Winterfell.",
				"Rode a dragon.",
				"Banged my aunt on a boat."
			],
			"role":"King of Westoros (low key)"
		}
	],
	"externalProfiles":{
		"github":"holistic-web",
		"linkedIn":"jon-snow-691533183"
	},
	"name":{
		"first":"Jon",
		"last":"Snow"
	},
	"profession":"Bastard",
	"profileImageUrl":"https://pbs.twimg.com/profile_images/901947348699545601/hqRMHITj_400x400.jpg"
}
